import type { TradeRecord } from "@/api/types";

/** Canonical TradeRecord test fixture builder — every field defaulted, override what you need. */
export function makeTradeRecord(overrides: Partial<TradeRecord> = {}): TradeRecord {
  return {
    trade_id: "trade:position-1:1",
    position_id: "position-1",
    instance_id: "instance_1",
    side: "long",
    status: "closed",
    entry_bar_index: 0,
    exit_bar_index: 1,
    entry_time_ms: 100_000,
    exit_time_ms: 200_000,
    entry_price: "1",
    exit_price: "2",
    quantity: "1",
    entry_notional: "1",
    exit_notional: "2",
    gross_pnl: "1",
    entry_fee: "0",
    exit_fee: "0",
    fees_paid: "0",
    net_pnl: "1",
    gross_return_pct: "0.01",
    net_return_pct: "0.01",
    equity_before: "1000",
    equity_after: "1001",
    hold_bars: 1,
    hold_ms: 100_000,
    exit_candidate_type: "signal",
    exit_reason: "signal:foo",
    exit_layer: "static",
    exit_rule_id: null,
    exit_component_id: null,
    exit_kind: null,
    path: {
      mfe_price: "2",
      mfe_pct: "0.02",
      mfe_bar_index: 1,
      mfe_bars_from_entry: 1,
      mae_price: "0.9",
      mae_pct: "0.01",
      mae_bar_index: 0,
      mae_bars_from_entry: 0,
      captured_price: "2",
      captured_pct: "0.01",
      capture_ratio: "0.5",
      giveback_price: "0.1",
      giveback_pct: "0.01",
      bars_from_mfe_to_exit: 0,
    },
    ...overrides,
  };
}
